### ISSUE TITLE
Throwing Fatal error

### ISSUE THREAD

**Issue by Chandram81** [wkdwilliams/LewScanner#1]
Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/chandram/repo/LewScanner/functions.php:24
Stack trace:
#0 /home/chandram/repo/LewScanner/functions.php(38): getHTTPCode()
#1 /home/chandram/repo/LewScanner/scan.php(33): httpIsRedirect()
#2 {main}
  thrown in /home/chandram/repo/LewScanner/functions.php on line 24

**Comment by wkdwilliams** [comment]
You must have php-curl installed. On Debian/Ubuntu, it's apt-get install php7.4-curl
